### ISSUE TITLE
Forked it up

### ISSUE THREAD

**Issue by joakim** [jonathanwiesel/slackus#1]
Hi!

I started with an innocent fork just to use [chuga's node-slack fork](https://github.com/chuga/node-slack) (the original no longer worked) and to tweak the configuration to match.

But I got carried away, and after a couple of hours had completely refactored the little app. I hope you don't mind! We'll be using the fork at our company, but if you think what I did is any good, you're of course welcome to take it (back?). If not, we'll just keep using it for ourselves.

The commit log sums up the changes I've made reasonably well.

It's all in the "kollegorna" branch:
https://github.com/kollegorna/slackus/tree/kollegorna

Best,
Joakim

**Comment by jonathanwiesel** [comment]
Closing as the reference fork has being merged
